# numpy full course

In [3]:
               # 0D array
import numpy as np
a=np.array(45)
print(a)
print(a.ndim)

45
0


In [2]:
               # 1D array
import numpy as np
a=np.array([3,4,5,6])
print(a)

[3 4 5 6]


In [3]:
               # 2D array
import numpy as np
a=np.array([[3,4,5,6],[1,2,3,4]])
print(a)

[[3 4 5 6]
 [1 2 3 4]]


In [4]:
               # 3D array
import numpy as np
a=np.array([[[3,4,5,6],[1,2,3,4]],[[3,4,5,6],[1,2,3,4]]])

print(a)
print(a.ndim)

[[[3 4 5 6]
  [1 2 3 4]]

 [[3 4 5 6]
  [1 2 3 4]]]
3


# dtype

In [5]:
                                            # dtype
a=np.array([1,2,3],dtype=float)
print(a)

[1. 2. 3.]


# arange-function

In [6]:
                                            # arange function
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
a=np.arange(15)

In [8]:
                                            # arange function
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [9]:
a=np.arange(1,15,3)
print(a)

[ 1  4  7 10 13]


# RESHAPE-FUNCTION

In [10]:
a=np.arange(16).reshape(2,8)
print(a)
print(a.dtype)
print(a.size)
print(a.shape)


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
int32
16
(2, 8)


# np.zeros

In [11]:
                          #np.zeros
a=np.zeros((2,2))
print(a)
                                

[[0. 0.]
 [0. 0.]]


In [12]:
a=np.ones((2,2,2,2))
print(a)

[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]]


# np.random

In [5]:
                                        # np.random
a=np.random.random((3,4))
a

array([[0.96924848, 0.85158857, 0.08166487, 0.7112958 ],
       [0.01797569, 0.72950706, 0.38813662, 0.16586197],
       [0.64593426, 0.84862024, 0.2021027 , 0.71126557]])

# np.linspace

In [14]:
a=np.linspace(1,5,10)        # (start,end,no of elements)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


# np.identity

In [15]:
a=np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# ravel

In [16]:
a=a.ravel()
print(a)

[1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 1.]


#   Axis

In [17]:
a=np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [18]:

                    # axis=0 means column 
a=np.arange(12).reshape(4,3)
print(a)
c=a.sum(axis=0)
print(c)
                    # axis=1 means rows 
a=np.arange(12).reshape(4,3)
print(a)
a=a.sum(axis=1)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[18 22 26]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 3 12 21 30]


In [19]:
                    # axis=0 means column 
a=np.arange(12).reshape(4,3)
print(a)
c=a.prod(axis=0)
print(c)

                    # axis=1 means rows 
a=np.arange(12).reshape(4,3)
print(a)
a=a.prod(axis=1)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[  0 280 880]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[  0  60 336 990]


# transpose

In [20]:
a=np.arange(12).reshape(4,3)
print(a)
t=a.T
print(t)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


#  flat-function 

In [21]:
a=np.arange(12).reshape(4,3)
print(a)
a.flat
for i in a.flat:
    print(i)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


# argsort / argmax /argmin

In [22]:
a=np.array([1,2,66,4,88,4])      #   maximum value is on index 4
print(a.argmax())

4


In [23]:
a=np.array([1,2,66,4,88,4])      #   minimum value is on index 0
print(a.argmin())

0


In [24]:
                                # sorting according to index
a=np.array([1,2,66,4,88,4])
print(a.argsort())

[0 1 3 5 2 4]


In [25]:
a=np.arange(12).reshape(4,3)
print(a)
print(a.argmax())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
11


In [26]:
print(a.argmax(axis=0))

[3 3 3]


In [27]:
print(a.argmax(axis=1))

[2 2 2 2]


In [28]:
print(a.argsort())

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]


# addition of two matrix

In [35]:
a=np.arange(12).reshape(4,3)
print(a)
b=np.array([[3,3,3],[3,3,3],[3,3,3],[3,3,3]])
print(b)
c=a+b
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# multiplication of two matrix

In [34]:
a=np.arange(12).reshape(4,3)
print(a)
b=np.array([[3,3,3],[3,3,3],[3,3,3],[3,3,3]])
print(b)
c=a*b
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]
 [27 30 33]]


# squire root

In [38]:
a=np.arange(12).reshape(4,3)
print(a)
np.sqrt(a)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

# for search an elements

In [41]:
a=np.arange(12).reshape(4,3)
print(a)
print(np.where(a>5))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(array([2, 2, 2, 3, 3, 3], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64))


# Indexing & slicing

In [45]:
a=np.arange(27).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [49]:
a[2,0,2]

20

In [50]:
a[1,1,1]

13

In [53]:
a[2,0:2,1:3]

array([[19, 20],
       [22, 23]])

In [54]:
a[2,0:3:2,0:3:2]

array([[18, 20],
       [24, 26]])

In [55]:
a=np.arange(27).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [58]:
a[0:3:2,0:3:3,0:3:2]

array([[[ 0,  2]],

       [[18, 20]]])

In [4]:
import numpy  as np
list1=np.array([1,2,3,4])
list2=np.array([1,2,3,4])
print(np.add(list1,list2))

[2 4 6 8]
